# Generated by Django 5.2.8 on 2025-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
